# -*- coding: utf-8 -*-
"""enzode-pandas-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfAYCACdrj_wQR0yDjp_ZPyjDpue01HO
"""

import pandas as pd


url = "http://51.91.120.89/PAD2603/mcdonalds.csv"
df = pd.read_csv(url)

df.columns

df.query(" Calories>=800 and TotalFat>60 ") # pokazuje tylko posilki >=800 kcal i >60g tłuszczu

df.query(" `Trans Fat` > 1")

df['Calories'].mean(), df['Calories'].max(), df['Calories'].min(), df['Calories'].median()

# Zawodnicy NBA
df = pd.read_csv("http://51.91.120.89/PAD2603/nba.csv")


df["Weight"] = df["Weight"] / 2.2
df.head(10)

def imp2metric(s):
  #6-6
  feet, inches = s.split("-")
  return int(feet)*30.2 + int(inches)*2.54

df.dropna(axis=0, how="all", inplace=True)
df.tail()

df["Height_cm"] = df["Height"].apply(imp2metric)

df.head()

df["College"].replace(pd.np.NaN, "", inplace=True)

df.head(10)

df.to_csv("nba.csv")

