# Generated by Django 3.2.3 on 2021-06-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(max_length=1024, verbose_name='Opis')),
                ('released', models.DateField(null=True, verbose_name='Data premiery')),
                ('year', models.IntegerField(blank=True, editable=False, null=True)),
                ('imdb', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Ocena')),
                ('trailer', models.URLField(null=True, verbose_name='Link do trailera')),
                ('poster', models.ImageField(null=True, upload_to='', verbose_name='Plakat')),
                ('mpaa_rating', models.CharField(choices=[('-', 'Brak'), ('PG-13', 'Za zgodą rodziców'), ('NC-17', 'Powyżej 17-go roku życia')], default='-', max_length=100, verbose_name='Rating MPAA')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
