# Generated by Django 3.2.3 on 2021-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210601_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(blank=True, null=True, verbose_name='Data premiery'),
        ),
    ]
