version: '3'

services:

    api:
        build: ./api
        env_file:
            - api.env
        command: uvicorn main:app --host 0.0.0.0 --port 80
        networks:
            - docker_network
    
    server:
        build: ./server
        depends_on:
            - api
        networks:
            - docker_network
        ports:
            - 8000:80

networks:
    docker_network:
        driver: bridge
